/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author andrespinzon
 */
public class Imagen extends javax.swing.JInternalFrame {
    
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de imagen", "png");
    String rutaimagen;

    /**
     * Creates new form Imagen
     */
    public Imagen() {
        initComponents();
        rutaimagen = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Subir_btn = new javax.swing.JButton();
        ruta_lbl = new javax.swing.JLabel();
        Imagen_lbl = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Imagen");

        Subir_btn.setText("Subir imagen");
        Subir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subir_btnActionPerformed(evt);
            }
        });

        ruta_lbl.setText("/Ruta");

        Imagen_lbl.setBackground(new java.awt.Color(255, 255, 255));
        Imagen_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen_lbl.setText("Imagen");
        Imagen_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ruta_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Imagen_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(Subir_btn)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Subir_btn)
                        .addGap(277, 277, 277))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Imagen_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(ruta_lbl)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Subir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subir_btnActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(filter);
        int opc = fc.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION) {
            String path = fc.getSelectedFile().getPath();
            String file = fc.getSelectedFile().toString();
            Imagen_lbl.setIcon(new ImageIcon(path));
            ImageIcon icon = new ImageIcon(path);
            Image img = icon.getImage();
            Image newimg = img.getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newimg);
            Imagen_lbl.setIcon(newIcon);
            Imagen_lbl.setSize(250, 250);
            ruta_lbl.setText(path);
            rutaimagen="";
        }
    }//GEN-LAST:event_Subir_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen_lbl;
    private javax.swing.JButton Subir_btn;
    private javax.swing.JLabel ruta_lbl;
    // End of variables declaration//GEN-END:variables
}
