/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author andrespinzon
 */
public class Midsquare extends javax.swing.JInternalFrame {

    /**
     * Creates new form Resultado
     */
    public Midsquare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Semilla_mid = new javax.swing.JTextField();
        Iteraciones_mid = new javax.swing.JTextField();
        Generar_mid = new javax.swing.JButton();
        Limpiar_mid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaX_mid = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaU_mid = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Generador Midsquare");
        setName(""); // NOI18N

        jLabel1.setText("Semilla:");

        jLabel2.setText("Iteraciones:");

        Semilla_mid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Semilla_midFocusLost(evt);
            }
        });

        Generar_mid.setText("Generar");
        Generar_mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generar_midActionPerformed(evt);
            }
        });

        Limpiar_mid.setText("Limpiar");
        Limpiar_mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_midActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListaX_mid);

        jScrollPane2.setViewportView(ListaU_mid);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("X");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("U");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Semilla_mid, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(Iteraciones_mid))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Limpiar_mid)
                            .addComponent(Generar_mid))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Semilla_mid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Generar_mid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Iteraciones_mid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Limpiar_mid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getAccessibleContext().setAccessibleName("Midsquare_frm");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Limpiar_midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_midActionPerformed
        DefaultListModel limpiar_mid = new DefaultListModel();
        Semilla_mid.setText("");
        Iteraciones_mid.setText("");
        ListaX_mid.setModel(limpiar_mid);
        ListaU_mid.setModel(limpiar_mid);
    }//GEN-LAST:event_Limpiar_midActionPerformed

    private void Generar_midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generar_midActionPerformed
        int ite = Integer.parseInt(Iteraciones_mid.getText());
        ArrayList<String> X = new ArrayList<String>();
        ArrayList<Double> U = new ArrayList<Double>();
        DefaultListModel listax = new DefaultListModel();
        DefaultListModel listau = new DefaultListModel();

        int x = Integer.parseInt(Semilla_mid.getText());
        for (int i = 0; i < ite; i++) {
            System.out.println("x^2=" + Math.pow(x, 2));
            //Elevo la semilla al cuadrado
            Double sqr = Math.pow(x, 2);
            String cadena = String.valueOf(sqr.intValue());

            //Evaluo si tiene menos de 4n digitos, si tiene menos completo con 0
            if (cadena.length() < 4) {
                cadena = 0 + cadena;
            }
            System.out.println("cadena=" + cadena);
            X.add(cadena.substring(1, 3));
            listax.addElement(cadena.substring(1, 3));
            ListaX_mid.setModel(listax);
            x = Integer.parseInt(cadena.substring(1, 3));
            //Asigno U
            listau.addElement("0." + cadena.substring(1, 3));
            ListaU_mid.setModel(listau);
        }
    }//GEN-LAST:event_Generar_midActionPerformed

    private void Semilla_midFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Semilla_midFocusLost

        if (Integer.parseInt(Semilla_mid.getText()) < 10 || Integer.parseInt(Semilla_mid.getText()) > 99 || 1 == Integer.parseInt(Semilla_mid.getText()) % 2) {
            showMessageDialog(null, "Debe ingresar un numero par de 2 digitos!");
        }


    }//GEN-LAST:event_Semilla_midFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Generar_mid;
    private javax.swing.JTextField Iteraciones_mid;
    private javax.swing.JButton Limpiar_mid;
    private javax.swing.JList<String> ListaU_mid;
    private javax.swing.JList<String> ListaX_mid;
    private javax.swing.JTextField Semilla_mid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
