/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generadores;

import Frames.Basico;
import Frames.Congruencial;
import Frames.Fibonacci;
import Frames.Midsquare;

/**
 *
 * @author andrespinzon
 */
public class Simulacion_frm extends javax.swing.JFrame {

    /**
     * Creates new form Simulacion_frm
     */
    public Simulacion_frm() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        Generadores_mn = new javax.swing.JMenuBar();
        Menu_mn = new javax.swing.JMenu();
        Basico_mn = new javax.swing.JMenuItem();
        Midsquare_mn = new javax.swing.JMenuItem();
        Congruencial_lineal_mn = new javax.swing.JMenuItem();
        Fibonacci_mn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir_mn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(getPreferredSize());

        Menu_mn.setText("Generadores");

        Basico_mn.setText("Básico");
        Basico_mn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Basico_mnActionPerformed(evt);
            }
        });
        Menu_mn.add(Basico_mn);

        Midsquare_mn.setText("Midsquare");
        Midsquare_mn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Midsquare_mnActionPerformed(evt);
            }
        });
        Menu_mn.add(Midsquare_mn);

        Congruencial_lineal_mn.setText("Congruencial lineal");
        Congruencial_lineal_mn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Congruencial_lineal_mnActionPerformed(evt);
            }
        });
        Menu_mn.add(Congruencial_lineal_mn);
        Congruencial_lineal_mn.getAccessibleContext().setAccessibleName("Congruencial");

        Fibonacci_mn.setText("Fibonacci");
        Fibonacci_mn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fibonacci_mnActionPerformed(evt);
            }
        });
        Menu_mn.add(Fibonacci_mn);
        Menu_mn.add(jSeparator1);

        Salir_mn.setText("Salir");
        Salir_mn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_mnActionPerformed(evt);
            }
        });
        Menu_mn.add(Salir_mn);
        Salir_mn.getAccessibleContext().setAccessibleName("Salir_opc");

        Generadores_mn.add(Menu_mn);
        Menu_mn.getAccessibleContext().setAccessibleName("Generadores_mn");
        Menu_mn.getAccessibleContext().setAccessibleDescription("");

        setJMenuBar(Generadores_mn);
        Generadores_mn.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Salir_mnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_mnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Salir_mnActionPerformed

    private void Basico_mnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Basico_mnActionPerformed
        Basico b = new Basico();
        Desktop.add(b);
        b.setVisible(true);
    }//GEN-LAST:event_Basico_mnActionPerformed

    private void Midsquare_mnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Midsquare_mnActionPerformed
        Midsquare mid = new Midsquare();
        Desktop.add(mid);
        mid.setVisible(true);
    }//GEN-LAST:event_Midsquare_mnActionPerformed

    private void Congruencial_lineal_mnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Congruencial_lineal_mnActionPerformed
        Congruencial cgr = new Congruencial();
        Desktop.add(cgr);
        cgr.setVisible(true);
    }//GEN-LAST:event_Congruencial_lineal_mnActionPerformed

    private void Fibonacci_mnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fibonacci_mnActionPerformed
        Fibonacci fib = new Fibonacci();
        Desktop.add(fib);
        fib.setVisible(true);
    }//GEN-LAST:event_Fibonacci_mnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulacion_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulacion_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulacion_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulacion_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulacion_frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Basico_mn;
    private javax.swing.JMenuItem Congruencial_lineal_mn;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem Fibonacci_mn;
    private javax.swing.JMenuBar Generadores_mn;
    private javax.swing.JMenu Menu_mn;
    private javax.swing.JMenuItem Midsquare_mn;
    private javax.swing.JMenuItem Salir_mn;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
